version: "3.5"

networks:
  my-awesome-network:

services:
  web-server:
    image: zulfadzlyrazak/alpine-httpd-fpm:latest
    container_name: '${WEB_SERVER_CONTAINER_NAME}'
    restart: 'always'
    ports:
      - '${PHP8_LOCAL_PORT}:${PHP8_CONTAINER_PORT}'
      - '${PHP7_LOCAL_PORT}:${PHP7_CONTAINER_PORT}'
    volumes:
      - './myapp:/var/www/myapp'
      - './apache/php-fpm.conf:/usr/local/apache2/conf/php-fpm.conf'
    depends_on:
      - 'php-server-8'
      - 'php-server-7'
      - 'db-server'
    networks:
      - 'my-awesome-network'

  php-server-8:
    image: zulfadzlyrazak/php8-fpm:latest
    container_name: '${PHP8_CONTAINER_NAME}'
    restart: 'always'
    volumes:
      - './myapp:/var/www/myapp'
    networks:
      - 'my-awesome-network'

  php-server-7:
    image: zulfadzlyrazak/php7-fpm:latest
    container_name: '${PHP7_CONTAINER_NAME}'
    restart: 'always'
    volumes:
      - './myapp:/var/www/myapp'
    networks:
      - 'my-awesome-network'

  db-server:
    image: mysql:8
    ports:
      - '${MYSQL_LOCAL_PORT}:${MYSQL_CONTAINER_PORT}'
    container_name: '${MYSQL_CONTAINER_NAME}'
    restart: 'always'
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_USER=${MYSQL_USER}'
    volumes:
      - './mysql-storage:/var/lib/mysql'
      - './mysql-config:/etc/mysql/conf.d'
      - './dumps:/docker-entrypoint-initdb.d'
    networks:
      - 'my-awesome-network'

  phpmyadmin:
    image: phpmyadmin
    container_name: '${PHPMYADMIN_CONTAINER_NAME}'
    restart: 'always'
    ports:
      - '${PHPMYADMIN_LOCAL_PORT}:${PHPMYADMIN_CONTAINER_PORT}'
    environment:
      - 'PMA_ARBITRARY=1'
      - 'PMA_HOST=${PHPMYADMIN_HOST}'
      - 'PMA_PORT=${MYSQL_CONTAINER_PORT}'
    depends_on:
      - 'db-server'
    networks:
      - 'my-awesome-network'
